// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddDeepOceanLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDDEEPOCEANLAYER
public:
    class AddDeepOceanLayer& operator=(class AddDeepOceanLayer const &) = delete;
    AddDeepOceanLayer(class AddDeepOceanLayer const &) = delete;
    AddDeepOceanLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddDeepOceanLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDDEEPOCEANLAYER
#endif

};