// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddEdgeLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDEDGELAYER
public:
    class AddEdgeLayer& operator=(class AddEdgeLayer const &) = delete;
    AddEdgeLayer(class AddEdgeLayer const &) = delete;
    AddEdgeLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddEdgeLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDEDGELAYER
#endif
    MCAPI void fillCoolWarm(class LayerData &, int, int, int, int);
    MCAPI void fillHeatIce(class LayerData &, int, int, int, int);
    MCAPI void fillIntroduceSpecial(class LayerData &, int, int, int, int);

};