// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddIslandLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDISLANDLAYER
public:
    class AddIslandLayer& operator=(class AddIslandLayer const &) = delete;
    AddIslandLayer(class AddIslandLayer const &) = delete;
    AddIslandLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddIslandLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDISLANDLAYER
#endif

};