// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddOceanTemperatureLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDOCEANTEMPERATURELAYER
public:
    class AddOceanTemperatureLayer& operator=(class AddOceanTemperatureLayer const &) = delete;
    AddOceanTemperatureLayer(class AddOceanTemperatureLayer const &) = delete;
    AddOceanTemperatureLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddOceanTemperatureLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDOCEANTEMPERATURELAYER
#endif

};