// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AddSnowLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ADDSNOWLAYER
public:
    class AddSnowLayer& operator=(class AddSnowLayer const &) = delete;
    AddSnowLayer(class AddSnowLayer const &) = delete;
    AddSnowLayer() = delete;
#endif

public:
    /*0*/ virtual ~AddSnowLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ADDSNOWLAYER
#endif

};