// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct AttributeDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ATTRIBUTEDESCRIPTION
public:
    struct AttributeDescription& operator=(struct AttributeDescription const &) = delete;
    AttributeDescription(struct AttributeDescription const &) = delete;
    AttributeDescription() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ATTRIBUTEDESCRIPTION
    MCVAPI char const * getNodeName() const;
#endif

};