// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

namespace Automation {

#define AFTER_EXTRA
// Add Member There
    enum MessagePurpose;
	class AutomationClient;
#undef AFTER_EXTRA
    MCAPI extern char const * BodyData;
    MCAPI extern char const * HeaderData;

};