// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BinaryDataOutput {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BINARYDATAOUTPUT
public:
    class BinaryDataOutput& operator=(class BinaryDataOutput const &) = delete;
    BinaryDataOutput(class BinaryDataOutput const &) = delete;
    BinaryDataOutput() = delete;
#endif

public:
    /*0*/ virtual ~BinaryDataOutput();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void writeFloat(float);
    /*4*/ virtual void writeDouble(double);
    /*5*/ virtual void writeByte(char);
    /*6*/ virtual void writeShort(short);
    /*7*/ virtual void writeInt(int);
    /*8*/ virtual void writeLongLong(__int64);
    /*9*/ virtual void writeBytes(void const *, unsigned __int64);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BINARYDATAOUTPUT
    MCVAPI void writeLongString(std::string const &);
    MCVAPI void writeString(std::string const &);
#endif

};