// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BiomeEdgeLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BIOMEEDGELAYER
public:
    class BiomeEdgeLayer& operator=(class BiomeEdgeLayer const &) = delete;
    BiomeEdgeLayer(class BiomeEdgeLayer const &) = delete;
    BiomeEdgeLayer() = delete;
#endif

public:
    /*0*/ virtual ~BiomeEdgeLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BIOMEEDGELAYER
#endif
    MCAPI bool checkEdgeStrict(class LayerData &, int, int, int, int, int, int);
    MCAPI bool isValidTemperatureEdge(int, int);

};