// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Blacklist {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLACKLIST
public:
    class Blacklist& operator=(class Blacklist const &) = delete;
    Blacklist(class Blacklist const &) = delete;
    Blacklist() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLACKLIST
#endif
    MCAPI void addEntry(struct Blacklist::Entry const &);
    MCAPI enum Blacklist::Duration getDuration(struct Blacklist::Entry const &) const;
    MCAPI std::string const & getMessage(struct Blacklist::Entry const &) const;
    MCAPI bool isBlocked(struct Blacklist::Entry const &) const;
    MCAPI void removeEntry(struct Blacklist::Entry const &);
    MCAPI ~Blacklist();

//private:
    MCAPI bool isBlocked(struct Blacklist::Entry const &, class std::_Vector_const_iterator<class std::_Vector_val<struct std::_Simple_types<struct Blacklist::Entry>>> &) const;

private:

};