// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

struct BlockQueuedTickingComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLOCKQUEUEDTICKINGCOMPONENT
public:
    struct BlockQueuedTickingComponent& operator=(struct BlockQueuedTickingComponent const &) = delete;
    BlockQueuedTickingComponent(struct BlockQueuedTickingComponent const &) = delete;
    BlockQueuedTickingComponent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLOCKQUEUEDTICKINGCOMPONENT
#endif
    MCAPI BlockQueuedTickingComponent(struct BlockQueuedTickingComponent &&);
    MCAPI ~BlockQueuedTickingComponent();

};