// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class CircuitTrackingInfo {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CIRCUITTRACKINGINFO
public:
    class CircuitTrackingInfo& operator=(class CircuitTrackingInfo const &) = delete;
    CircuitTrackingInfo() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CIRCUITTRACKINGINFO
#endif
    MCAPI CircuitTrackingInfo(class CircuitTrackingInfo const &);

};