// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

struct CommandOriginData {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRApublic:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_COMMANDORIGINDATA
#endif
    MCAPI CommandOriginData(struct CommandOriginData const &);
    MCAPI CommandOriginData();
    MCAPI struct CommandOriginData & operator=(struct CommandOriginData const &);
    MCAPI ~CommandOriginData();

};