// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct CustomScriptEventData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CUSTOMSCRIPTEVENTDATA
public:
    struct CustomScriptEventData& operator=(struct CustomScriptEventData const &) = delete;
    CustomScriptEventData(struct CustomScriptEventData const &) = delete;
    CustomScriptEventData() = delete;
#endif
public:
    /*0*/ virtual ~CustomScriptEventData();
    /*1*/ virtual bool _serialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CUSTOMSCRIPTEVENTDATA
#endif

};