// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"
#include "OverworldBiome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class DesertBiome : public OverworldBiome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DESERTBIOME
public:
    class DesertBiome& operator=(class DesertBiome const &) = delete;
    DesertBiome(class DesertBiome const &) = delete;
    DesertBiome() = delete;
#endif

public:
    /*3*/ virtual ~DesertBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_DESERTBIOME
#endif

};