// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class DimensionHeightRange {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DIMENSIONHEIGHTRANGE
public:
    class DimensionHeightRange& operator=(class DimensionHeightRange const &) = delete;
    DimensionHeightRange(class DimensionHeightRange const &) = delete;
    DimensionHeightRange() = delete;
#endif

public:
    MCAPI DimensionHeightRange(short, short);

protected:

private:

};