// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Packet.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ExplodePacket : public Packet {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EXPLODEPACKET
public:
    class ExplodePacket& operator=(class ExplodePacket const &) = delete;
    ExplodePacket(class ExplodePacket const &) = delete;
    ExplodePacket() = delete;
#endif

public:
    /*0*/ virtual ~ExplodePacket();
    /*1*/ virtual enum MinecraftPacketIds getId() const;
    /*2*/ virtual std::string getName() const;
    /*3*/ virtual void write(class BinaryStream &) const;
    /*4*/ virtual enum PacketReadResult read(class BinaryStream &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EXPLODEPACKET
#endif

};