// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"
#include "OverworldBiome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ExtremeHillsBiome : public OverworldBiome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EXTREMEHILLSBIOME
public:
    class ExtremeHillsBiome& operator=(class ExtremeHillsBiome const &) = delete;
    ExtremeHillsBiome(class ExtremeHillsBiome const &) = delete;
    ExtremeHillsBiome() = delete;
#endif

public:
    /*3*/ virtual ~ExtremeHillsBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*22*/ virtual std::unique_ptr<class Biome> createMutatedCopy(int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EXTREMEHILLSBIOME
#endif
    MCAPI ExtremeHillsBiome(int, bool);

};