// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "VillagePiece.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Farmland : public VillagePiece {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FARMLAND
public:
    class Farmland& operator=(class Farmland const &) = delete;
    Farmland(class Farmland const &) = delete;
    Farmland() = delete;
#endif

public:
    /*0*/ virtual ~Farmland();
    /*2*/ virtual enum StructurePieceType getType() const;
    /*4*/ virtual bool postProcess(class BlockSource *, class Random &, class BoundingBox const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_FARMLAND
#endif
    MCAPI static class Block const & selectCrops(class Random &, class StartPiece &);

};