// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class FurnaceRecipes {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_FURNACERECIPES
public:
    class FurnaceRecipes& operator=(class FurnaceRecipes const &) = delete;
    FurnaceRecipes(class FurnaceRecipes const &) = delete;
    FurnaceRecipes() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_FURNACERECIPES
#endif
    MCAPI void addFurnaceRecipe(class Item const &, class ItemInstance const &);
    MCAPI void addFurnaceRecipe(class BlockLegacy const &, class ItemInstance const &);
    MCAPI void addFurnaceRecipeAuxData(class BlockLegacy const &, short, class ItemInstance const &);
    MCAPI void clearFurnaceRecipes();
    MCAPI class ItemInstance getResult(class ItemInstance const &) const;
    MCAPI void init();

};