// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct IActorMovementProxy {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_IACTORMOVEMENTPROXY
public:
    struct IActorMovementProxy& operator=(struct IActorMovementProxy const &) = delete;
    IActorMovementProxy(struct IActorMovementProxy const &) = delete;
    IActorMovementProxy() = delete;
#endif

public:
    MCAPI class gsl::not_null<struct IPlayerMovementProxy *> asPlayer();

protected:

private:

};