// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class InitialTickFilterSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_INITIALTICKFILTERSYSTEM
public:
    class InitialTickFilterSystem& operator=(class InitialTickFilterSystem const &) = delete;
    InitialTickFilterSystem(class InitialTickFilterSystem const &) = delete;
    InitialTickFilterSystem() = delete;
#endif

public:
    MCAPI static void blockFilterTickEntity(class StrictEntityContext &, class FlagComponent<struct UsesECSMovementFlag> const &, class FlagComponent<struct ActorMovementTickNeededFlag> const &, struct ConstBlockSourceComponent const &, struct StateVectorComponent const &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct ActorMovementTickNeededFlag>> &);
    MCAPI static struct TickingSystemWithInfo createBlockFilterSystem();
    MCAPI static struct TickingSystemWithInfo createTickingAreaFilterSystem();
    MCAPI static void tickingAreaFilterTickEntity(class StrictEntityContext &, class FlagComponent<struct UsesECSMovementFlag> const &, class FlagComponent<struct ActorMovementTickNeededFlag> const &, class TickWorldComponent &, struct CurrentTickComponent const &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct ActorMovementTickNeededFlag>> &);

protected:

private:
    MCAPI static void _tickingAreaFilterTickView(class OptionalGlobalT<struct CurrentTickComponent const, class EntityRegistryBase>, class ViewT<class StrictEntityContext, class EntityRegistryBase, class FlagComponent<struct UsesECSMovementFlag> const, class FlagComponent<struct ActorMovementTickNeededFlag> const, class TickWorldComponent>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct ActorMovementTickNeededFlag>>);

};