// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class InteractNode {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_INTERACTNODE
public:
    class InteractNode& operator=(class InteractNode const &) = delete;
    InteractNode(class InteractNode const &) = delete;
    InteractNode() = delete;
#endif

public:
    /*0*/ virtual ~InteractNode();
    /*1*/ virtual enum BehaviorStatus tick();
    /*2*/ virtual void initializeFromDefinition();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_INTERACTNODE
#endif

};