// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ItemUseOnEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ITEMUSEONEVENT
public:
    struct ItemUseOnEvent& operator=(struct ItemUseOnEvent const &) = delete;
    ItemUseOnEvent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ITEMUSEONEVENT
#endif
    MCAPI ItemUseOnEvent(struct ItemUseOnEvent &&);
    MCAPI ItemUseOnEvent(struct ItemUseOnEvent const &);
    MCAPI ~ItemUseOnEvent();

};