// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class KnockbackResistanceItemComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_KNOCKBACKRESISTANCEITEMCOMPONENT
public:
    class KnockbackResistanceItemComponent& operator=(class KnockbackResistanceItemComponent const &) = delete;
    KnockbackResistanceItemComponent(class KnockbackResistanceItemComponent const &) = delete;
    KnockbackResistanceItemComponent() = delete;
#endif

public:
    /*0*/ virtual ~KnockbackResistanceItemComponent();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    MCAPI float getProtectionValue() const;
    MCAPI static void bindType();
    MCAPI static class HashedString const & getIdentifier();

protected:

private:

};