// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LargeCaveFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LARGECAVEFEATURE
public:
    class LargeCaveFeature& operator=(class LargeCaveFeature const &) = delete;
    LargeCaveFeature(class LargeCaveFeature const &) = delete;
    LargeCaveFeature() = delete;
#endif

public:
    /*0*/ virtual ~LargeCaveFeature();
    /*1*/ virtual bool carve(class BlockVolume &, class BiomeSource &, class Random &, class ChunkPos const &, class Vec3 const &, class Vec3 const &, int, int, int, int, int, int, float, float) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LARGECAVEFEATURE
#endif
    MCAPI void apply(class BlockVolume &, class ChunkPos const &, class Dimension &, class Random &);

//protected:
    MCAPI void addFeature(class BlockVolume &, class BiomeSource &, class ChunkPos const &, class Random &, int, int);
    MCAPI void addTunnel(class BlockVolume &, class BiomeSource &, class Random &, class ChunkPos const &, class Vec3 const &, class Vec3 const &, float, float, float, int, int, float) const;

protected:

};