// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LAYER
public:
    class Layer& operator=(class Layer const &) = delete;
    Layer(class Layer const &) = delete;
    Layer() = delete;
#endif

public:
    /*0*/ virtual ~Layer();
    /*1*/ virtual void init(__int64);
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
    /*3*/ virtual int _modeOrRandom(int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LAYER
#endif

//protected:
    MCAPI static bool _isOcean(int);
    MCAPI static bool _isSame(class BiomeRegistry const &, int, int);
    MCAPI static bool _isShallowOcean(int);

protected:

};