// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MegaTreeFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MEGATREEFEATURE
public:
    class MegaTreeFeature& operator=(class MegaTreeFeature const &) = delete;
    MegaTreeFeature(class MegaTreeFeature const &) = delete;
    MegaTreeFeature() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MEGATREEFEATURE
#endif

//protected:
    MCAPI int _calcTreeHeigth(class Random &) const;
    MCAPI bool _makeDirtFloor(class BlockSource &, class BlockPos const &) const;
    MCAPI void _placeDoubleTrunkLeaves(class BlockSource &, class BlockPos const &, int) const;
    MCAPI void _placeSingleTrunkLeaves(class BlockSource &, class BlockPos const &, int) const;
    MCAPI bool _prepareTree(class BlockSource &, class BlockPos const &, int) const;

protected:

};