// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MetaDataTypeVisitor_Get {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_METADATATYPEVISITOR_GET
public:
    class MetaDataTypeVisitor_Get& operator=(class MetaDataTypeVisitor_Get const &) = delete;
    MetaDataTypeVisitor_Get(class MetaDataTypeVisitor_Get const &) = delete;
    MetaDataTypeVisitor_Get() = delete;
#endif

public:
    MCAPI class std::optional<class std::variant<class BaseGameVersion, std::string, class LevelSeed64, enum GeneratorType, bool, short, class DimensionHeightRange>> operator()(class DimensionHeightRange const &) const;
    MCAPI ~MetaDataTypeVisitor_Get();

protected:

private:

};