// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class NetherBiome : public Biome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_NETHERBIOME
public:
    class NetherBiome& operator=(class NetherBiome const &) = delete;
    NetherBiome(class NetherBiome const &) = delete;
    NetherBiome() = delete;
#endif

public:
    /*3*/ virtual ~NetherBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*8*/ virtual float getCreatureProbability();
    /*16*/ virtual void decorate(class BlockSource *, class Random &, class BlockPos const &, bool, float);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_NETHERBIOME
#endif

};