// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class NetworkPacketEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_NETWORKPACKETEVENTLISTENER
public:
    class NetworkPacketEventListener& operator=(class NetworkPacketEventListener const &) = delete;
    NetworkPacketEventListener(class NetworkPacketEventListener const &) = delete;
    NetworkPacketEventListener() = delete;
#endif

public:
    /*0*/ virtual ~NetworkPacketEventListener();
    /*1*/ virtual enum EventResult onPacketReceivedFrom(class PacketHeader const &, class Packet const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_NETWORKPACKETEVENTLISTENER
#endif

};