// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"
#include "OverworldBiome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OceanFrozenBiome : public OverworldBiome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OCEANFROZENBIOME
public:
    class OceanFrozenBiome& operator=(class OceanFrozenBiome const &) = delete;
    OceanFrozenBiome(class OceanFrozenBiome const &) = delete;
    OceanFrozenBiome() = delete;
#endif

public:
    /*3*/ virtual ~OceanFrozenBiome();
    /*4*/ virtual float getTemperatureWorldGen(class BlockPos const &) const;
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*8*/ virtual float getCreatureProbability();
    /*19*/ virtual enum Biome::BiomeTempCategory getTemperatureCategory() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OCEANFROZENBIOME
#endif

};