// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"
#include "OverworldBiome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OceanColdBiome : public OverworldBiome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OCEANCOLDBIOME
public:
    class OceanColdBiome& operator=(class OceanColdBiome const &) = delete;
    OceanColdBiome(class OceanColdBiome const &) = delete;
    OceanColdBiome() = delete;
#endif

public:
    /*3*/ virtual ~OceanColdBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*8*/ virtual float getCreatureProbability();
    /*19*/ virtual enum Biome::BiomeTempCategory getTemperatureCategory() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OCEANCOLDBIOME
#endif

};