// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OceanMixerLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OCEANMIXERLAYER
public:
    class OceanMixerLayer& operator=(class OceanMixerLayer const &) = delete;
    OceanMixerLayer(class OceanMixerLayer const &) = delete;
    OceanMixerLayer() = delete;
#endif

public:
    /*0*/ virtual ~OceanMixerLayer();
    /*1*/ virtual void init(__int64);
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OCEANMIXERLAYER
#endif

};