// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OculusPlatformMessagePump {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OCULUSPLATFORMMESSAGEPUMP
public:
    class OculusPlatformMessagePump& operator=(class OculusPlatformMessagePump const &) = delete;
    OculusPlatformMessagePump(class OculusPlatformMessagePump const &) = delete;
    OculusPlatformMessagePump() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OCULUSPLATFORMMESSAGEPUMP
#endif
    MCAPI static std::string const mOculusAppId;

};