// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct PackInstanceId {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PACKINSTANCEID
public:
    struct PackInstanceId& operator=(struct PackInstanceId const &) = delete;
    PackInstanceId(struct PackInstanceId const &) = delete;
    PackInstanceId() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PACKINSTANCEID
#endif
    MCAPI PackInstanceId(struct PackInstanceId &&);
    MCAPI PackInstanceId(struct PackIdVersion const &, std::string const &);
    MCAPI ~PackInstanceId();

};