// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Command.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PermissionsCommand : public Command {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PERMISSIONSCOMMAND
public:
    class PermissionsCommand& operator=(class PermissionsCommand const &) = delete;
    PermissionsCommand(class PermissionsCommand const &) = delete;
    PermissionsCommand() = delete;
#endif

public:
    /*0*/ virtual ~PermissionsCommand();
    /*1*/ virtual void execute(class CommandOrigin const &, class CommandOutput &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PERMISSIONSCOMMAND
#endif
    MCAPI static void setup(class CommandRegistry &, class PermissionsFile *);

//private:

private:
    MCAPI static class PermissionsFile * mPermissionsFile;

};