// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PoolAllocator {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_POOLALLOCATOR
public:
    class PoolAllocator& operator=(class PoolAllocator const &) = delete;
    PoolAllocator(class PoolAllocator const &) = delete;
    PoolAllocator() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_POOLALLOCATOR
#endif
    MCAPI void * get();
    MCAPI ~PoolAllocator();

};