// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct PropertyDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PROPERTYDESCRIPTION
public:
    struct PropertyDescription& operator=(struct PropertyDescription const &) = delete;
    PropertyDescription(struct PropertyDescription const &) = delete;
    PropertyDescription() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PROPERTYDESCRIPTION
    MCVAPI char const * getNodeName() const;
    MCVAPI ~PropertyDescription();
#endif

};