// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PumpkinFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PUMPKINFEATURE
public:
    class PumpkinFeature& operator=(class PumpkinFeature const &) = delete;
    PumpkinFeature(class PumpkinFeature const &) = delete;
    PumpkinFeature() = delete;
#endif

public:
    /*0*/ virtual ~PumpkinFeature();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    /*4*/ virtual bool place(class BlockSource &, class BlockPos const &, class Random &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PUMPKINFEATURE
#endif

};