// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RandomAuxValueFunction {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RANDOMAUXVALUEFUNCTION
public:
    class RandomAuxValueFunction& operator=(class RandomAuxValueFunction const &) = delete;
    RandomAuxValueFunction(class RandomAuxValueFunction const &) = delete;
    RandomAuxValueFunction() = delete;
#endif

public:
    /*0*/ virtual ~RandomAuxValueFunction();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void apply(class ItemInstance &, class Random &, class LootTableContext &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RANDOMAUXVALUEFUNCTION
#endif

};