// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ResourcePackInfoData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESOURCEPACKINFODATA
public:
    class ResourcePackInfoData& operator=(class ResourcePackInfoData const &) = delete;
    ResourcePackInfoData(class ResourcePackInfoData const &) = delete;
    ResourcePackInfoData() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESOURCEPACKINFODATA
#endif
    MCAPI ~ResourcePackInfoData();

};