// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RoofTreeFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ROOFTREEFEATURE
public:
    class RoofTreeFeature& operator=(class RoofTreeFeature const &) = delete;
    RoofTreeFeature(class RoofTreeFeature const &) = delete;
    RoofTreeFeature() = delete;
#endif

public:
    /*0*/ virtual ~RoofTreeFeature();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    /*4*/ virtual bool place(class BlockSource &, class BlockPos const &, class Random &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ROOFTREEFEATURE
#endif

//private:
    MCAPI void _placeLeafAt(class BlockSource &, class BlockPos const &) const;
    MCAPI void _placeLeafs(class BlockSource &, class BlockPos const &, class BlockPos const &, class Random &) const;
    MCAPI void _placeVine(class BlockSource &, class BlockPos const &, class Random &, int) const;
    MCAPI void _placeVines(class BlockSource &, class BlockPos const &, class Random &, bool, int, int) const;

private:

};