// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ScriptServerActorCreatedEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERACTORCREATEDEVENT
public:
    struct ScriptServerActorCreatedEvent& operator=(struct ScriptServerActorCreatedEvent const &) = delete;
    ScriptServerActorCreatedEvent(struct ScriptServerActorCreatedEvent const &) = delete;
    ScriptServerActorCreatedEvent() = delete;
#endif
public:
    /*0*/ virtual ~ScriptServerActorCreatedEvent();
    /*1*/ virtual bool _serialize(class ScriptEngine &, class ScriptApi::ScriptObjectHandle &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERACTORCREATEDEVENT
#endif

};