// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptServerPacketEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERPACKETEVENTLISTENER
public:
    class ScriptServerPacketEventListener& operator=(class ScriptServerPacketEventListener const &) = delete;
    ScriptServerPacketEventListener(class ScriptServerPacketEventListener const &) = delete;
    ScriptServerPacketEventListener() = delete;
#endif

public:
    /*0*/ virtual ~ScriptServerPacketEventListener();
    /*1*/ virtual enum EventResult onPacketReceivedFrom(class PacketHeader const &, class Packet const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERPACKETEVENTLISTENER
#endif

};