// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptActorWrapper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTACTORWRAPPER
public:
    class ScriptActorWrapper& operator=(class ScriptActorWrapper const &) = delete;
    ScriptActorWrapper(class ScriptActorWrapper const &) = delete;
    ScriptActorWrapper() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTACTORWRAPPER
#endif
    MCAPI ~ScriptActorWrapper();

};