// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptDynamicPropertiesDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTDYNAMICPROPERTIESDEFINITION
public:
    class ScriptDynamicPropertiesDefinition& operator=(class ScriptDynamicPropertiesDefinition const &) = delete;
#endif

public:
    MCAPI ScriptDynamicPropertiesDefinition(class ScriptDynamicPropertiesDefinition const &);
    MCAPI ScriptDynamicPropertiesDefinition();
    MCAPI ScriptDynamicPropertiesDefinition(class ScriptDynamicPropertiesDefinition &&);
    MCAPI class Scripting::Result<void> defineBoolean(std::string const &);
    MCAPI class Scripting::Result<void> defineNumber(std::string const &);
    MCAPI class Scripting::Result<void> defineString(std::string const &, unsigned int);
    MCAPI class DynamicPropertiesDefinition const & getDefinition() const;
    MCAPI class ScriptDynamicPropertiesDefinition & operator=(class ScriptDynamicPropertiesDefinition &&);
    MCAPI ~ScriptDynamicPropertiesDefinition();
    MCAPI static class Scripting::ClassBindingBuilder<class ScriptDynamicPropertiesDefinition> bind(struct Scripting::Version);

protected:

private:

};