// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptServerBroadcastReceived {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERBROADCASTRECEIVED
public:
    class ScriptServerBroadcastReceived& operator=(class ScriptServerBroadcastReceived const &) = delete;
    ScriptServerBroadcastReceived(class ScriptServerBroadcastReceived const &) = delete;
    ScriptServerBroadcastReceived() = delete;
#endif

public:
    /*0*/ virtual ~ScriptServerBroadcastReceived();
    /*1*/ virtual bool receivedEvent(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, std::string const &, class ScriptApi::ScriptObjectHandle const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERBROADCASTRECEIVED
#endif

};