// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptSpawnActorComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSPAWNACTORCOMPONENT
public:
    class ScriptSpawnActorComponent& operator=(class ScriptSpawnActorComponent const &) = delete;
    ScriptSpawnActorComponent(class ScriptSpawnActorComponent const &) = delete;
    ScriptSpawnActorComponent() = delete;
#endif

public:
    /*0*/ virtual ~ScriptSpawnActorComponent();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual bool applyComponentTo(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Actor &, class ScriptApi::ScriptObjectHandle const &) const;
    /*3*/ virtual void __unk_vfn_3();
    /*4*/ virtual bool retrieveComponentFrom(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class ScriptServerContext &, class Actor &, class ScriptApi::ScriptObjectHandle &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSPAWNACTORCOMPONENT
#endif

};