// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ScriptApi {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI void * AddFilterToQueryChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * ApplyComponentChangesChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * BroadcastEventChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * CreateComponentChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * CreateEntityChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI enum _JsErrorCode DefineChakraCallback(void *, std::string const &, void * ( *)(void *, bool, void **, unsigned short, void *), void *, class ScriptApi::ScriptReport &);
    MCAPI void * DestroyComponentChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * DestroyEntityChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * GetComponentChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * GetEntitiesFromQueryChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * HasComponentChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * IsValidEntityChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI enum _JsErrorCode JsCreatePropertyIdHelper(std::string const &, void **);
    MCAPI enum _JsErrorCode JsGetStringHelper(void *, std::string &);
    MCAPI void * ListenForEventChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * LogChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * OnChakraEngineCall(void *, bool, void **, unsigned short, void *, class std::function<void (class ScriptApi::ScriptCallbackInterface &, std::vector<class ScriptApi::ScriptObjectHandle> const &, class ScriptApi::ScriptObjectHandle &)>);
    MCAPI void * RegisterComponentChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * RegisterQueryChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI void * RegisterSystemChakraCallback(void *, bool, void **, unsigned short, void *);
    MCAPI class std::basic_string<wchar_t, struct std::char_traits<wchar_t>, class std::allocator<wchar_t>> StringToWString(std::string const &);

};