// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptServerLevelEventListener {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTSERVERLEVELEVENTLISTENER
public:
    class ScriptServerLevelEventListener& operator=(class ScriptServerLevelEventListener const &) = delete;
    ScriptServerLevelEventListener(class ScriptServerLevelEventListener const &) = delete;
    ScriptServerLevelEventListener() = delete;
#endif

public:
    /*0*/ virtual ~ScriptServerLevelEventListener();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    /*4*/ virtual void __unk_vfn_4();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*7*/ virtual enum EventResult onLevelTick();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTSERVERLEVELEVENTLISTENER
#endif

};