// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Core.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptPackConfigurationManager {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTPACKCONFIGURATIONMANAGER
public:
    class ScriptPackConfigurationManager& operator=(class ScriptPackConfigurationManager const &) = delete;
#endif

public:
    /*0*/ virtual ~ScriptPackConfigurationManager();
    /*
    inline  ~ScriptPackConfigurationManager(){
         (ScriptPackConfigurationManager::*rv)();
        *((void**)&rv) = dlsym("??1ScriptPackConfigurationManager@@UEAA@XZ");
        return (this->*rv)();
    }
    */
    MCAPI ScriptPackConfigurationManager(class ScriptPackConfigurationManager const &);
    MCAPI ScriptPackConfigurationManager();
    MCAPI class ScriptPackConfiguration const & getPackConfiguration(std::string const &) const;
    MCAPI void loadPackConfigs(class Core::Path const &);

protected:

private:
    MCAPI static std::string const sDefaultConfigurationName;

};