// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptComponentWrapper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTCOMPONENTWRAPPER
public:
    class ScriptComponentWrapper& operator=(class ScriptComponentWrapper const &) = delete;
    ScriptComponentWrapper(class ScriptComponentWrapper const &) = delete;
    ScriptComponentWrapper() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTCOMPONENTWRAPPER
#endif
    MCAPI ~ScriptComponentWrapper();

};