// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ScriptApi.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptQueries {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTQUERIES
public:
    class ScriptQueries& operator=(class ScriptQueries const &) = delete;
    ScriptQueries(class ScriptQueries const &) = delete;
    ScriptQueries() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTQUERIES
#endif
    MCAPI bool getEntitiesFromQuery(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class entt::Registry<unsigned int> &, unsigned int, std::vector<class ScriptApi::ScriptObjectHandle> &);
    MCAPI bool getEntitiesFromQuery(class ScriptApi::ScriptVersionInfo const &, class ScriptEngine &, class entt::Registry<unsigned int> &, unsigned int, double, double, double, double, double, double, std::vector<class ScriptApi::ScriptObjectHandle> &);

};