// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptPureECSWrapper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTPUREECSWRAPPER
public:
    class ScriptPureECSWrapper& operator=(class ScriptPureECSWrapper const &) = delete;
    ScriptPureECSWrapper(class ScriptPureECSWrapper const &) = delete;
    ScriptPureECSWrapper() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTPUREECSWRAPPER
#endif
    MCAPI ~ScriptPureECSWrapper();

};