// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Sensing {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SENSING
public:
    class Sensing& operator=(class Sensing const &) = delete;
    Sensing(class Sensing const &) = delete;
    Sensing() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SENSING
#endif
    MCAPI bool canSee(class Actor const &);
    MCAPI bool withinFOV(class Mob &, class Vec3 const &, float);

};