// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Bedrock.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ServerScriptManager {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERSCRIPTMANAGER
public:
    class ServerScriptManager& operator=(class ServerScriptManager const &) = delete;
    ServerScriptManager(class ServerScriptManager const &) = delete;
    ServerScriptManager() = delete;
#endif

public:
    /*0*/ virtual ~ServerScriptManager();
    /*1*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*2*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*3*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*4*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*5*/ virtual enum EventResult onServerUpdateStart(class ServerInstance &);
    /*6*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*7*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*8*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*9*/ virtual enum EventResult onServerThreadStarted(class ServerInstance &);
    /*10*/ virtual enum EventResult onServerThreadStopped(class ServerInstance &);
    /*11*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*12*/ virtual enum EventResult onEvent(struct ServerInstanceRequestResourceReload const &);
    /*14*/ virtual enum EventResult onServerLevelInitialized(class ServerInstance &, class Level &);
    /*
    inline  ~ServerScriptManager(){
         (ServerScriptManager::*rv)();
        *((void**)&rv) = dlsym("??1ServerScriptManager@@UEAA@XZ");
        return (this->*rv)();
    }
    */
    MCAPI ServerScriptManager(struct ScriptSettings, class Bedrock::NonOwnerPointer<class Scheduler>);
    MCAPI void onMainThreadStartLeaveGame();

protected:

private:
    MCAPI void _loadAndRunAllPlugins(class Minecraft &, class ServerLevel &);
    MCAPI void _registerEventHandlers(class Level &) const;
    MCAPI void _sendInitializeEvent(class ServerLevel &) const;
    MCAPI void _unregisterEventHandlers(class Level &) const;

};