// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "SkinInfoData.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ServerSkinInfoData : public SkinInfoData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERSKININFODATA
public:
    class ServerSkinInfoData& operator=(class ServerSkinInfoData const &) = delete;
    ServerSkinInfoData(class ServerSkinInfoData const &) = delete;
    ServerSkinInfoData() = delete;
#endif

public:
    /*0*/ virtual ~ServerSkinInfoData();
    /*1*/ virtual void updateSkin(std::string const &, struct mce::Image const *const, struct mce::Image const *const, std::string const &, std::string const &, bool);
    /*2*/ virtual unsigned char const * getData();
    /*3*/ virtual int getDataLength();
    /*4*/ virtual bool hasValidTexture();
    /*5*/ virtual unsigned char const * getCapeData();
    /*6*/ virtual int getCapeDataLength();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERVERSKININFODATA
#endif

};