// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Layer.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ShoreLayer : public Layer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHORELAYER
public:
    class ShoreLayer& operator=(class ShoreLayer const &) = delete;
    ShoreLayer(class ShoreLayer const &) = delete;
    ShoreLayer() = delete;
#endif

public:
    /*0*/ virtual ~ShoreLayer();
    /*2*/ virtual void fillArea(class LayerData &, int, int, int, int);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHORELAYER
#endif

//private:
    MCAPI bool _isJungleCompatible(int);
    MCAPI bool _isMesa(int);
    MCAPI void _replaceIfNeighborOcean(class LayerData &, int, int, int, int, int);

private:

};