// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SkinInfoFactory {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SKININFOFACTORY
public:
    class SkinInfoFactory& operator=(class SkinInfoFactory const &) = delete;
    SkinInfoFactory(class SkinInfoFactory const &) = delete;
    SkinInfoFactory() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SKININFOFACTORY
#endif

};