// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "VillagePiece.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SmallHut : public VillagePiece {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SMALLHUT
public:
    class SmallHut& operator=(class SmallHut const &) = delete;
    SmallHut(class SmallHut const &) = delete;
    SmallHut() = delete;
#endif

public:
    /*0*/ virtual ~SmallHut();
    /*2*/ virtual enum StructurePieceType getType() const;
    /*4*/ virtual bool postProcess(class BlockSource *, class Random &, class BoundingBox const &);
    /*5*/ virtual void postProcessMobsAt(class BlockSource *, class Random &, class BoundingBox const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SMALLHUT
#endif
    MCAPI static std::unique_ptr<class VillagePiece> createPiece(class StartPiece *, std::vector<std::unique_ptr<class StructurePiece>> &, class Random &, int, int, int, int, int);

};