// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "VillagePiece.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class StraightRoad : public VillagePiece {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STRAIGHTROAD
public:
    class StraightRoad& operator=(class StraightRoad const &) = delete;
    StraightRoad(class StraightRoad const &) = delete;
    StraightRoad() = delete;
#endif

public:
    /*0*/ virtual ~StraightRoad();
    /*2*/ virtual enum StructurePieceType getType() const;
    /*3*/ virtual void addChildren(class StructurePiece *, std::vector<std::unique_ptr<class StructurePiece>> &, class Random &);
    /*4*/ virtual bool postProcess(class BlockSource *, class Random &, class BoundingBox const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STRAIGHTROAD
#endif
    MCAPI static class BoundingBox findPieceBox(class StartPiece *, std::vector<std::unique_ptr<class StructurePiece>> &, class Random &, int, int, int, int);

};