// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SubChunkBlockStorage {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SUBCHUNKBLOCKSTORAGE
public:
    class SubChunkBlockStorage& operator=(class SubChunkBlockStorage const &) = delete;
    SubChunkBlockStorage(class SubChunkBlockStorage const &) = delete;
    SubChunkBlockStorage() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SUBCHUNKBLOCKSTORAGE
    MCVAPI class ISubChunkBlockStoragePaletted * asPalettedStorage();
    MCVAPI class ISubChunkBlockStoragePaletted const * asPalettedStorage() const;
#endif
    MCAPI static std::unique_ptr<class SubChunkBlockStorage> makeDeserialized(class IDataInput &, class BlockPalette const &, enum SubChunkFormat);
    MCAPI static std::unique_ptr<class SubChunkBlockStorage> makeFromRawData(class buffer_span<class Block const *>, unsigned __int64);
    MCAPI static std::unique_ptr<class SubChunkBlockStorage> makeType(enum SubChunkBlockStorage::Type, class SubChunkBlockStorage const *);

};