// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SwampTreeFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SWAMPTREEFEATURE
public:
    class SwampTreeFeature& operator=(class SwampTreeFeature const &) = delete;
    SwampTreeFeature(class SwampTreeFeature const &) = delete;
    SwampTreeFeature() = delete;
#endif

public:
    /*0*/ virtual ~SwampTreeFeature();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    /*4*/ virtual bool place(class BlockSource &, class BlockPos const &, class Random &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SWAMPTREEFEATURE
#endif

//private:
    MCAPI void _addVine(class BlockSource &, class BlockPos, int) const;

private:

};