// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"
#include "OverworldBiome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SwampBiome : public OverworldBiome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SWAMPBIOME
public:
    class SwampBiome& operator=(class SwampBiome const &) = delete;
    SwampBiome(class SwampBiome const &) = delete;
    SwampBiome() = delete;
#endif

public:
    /*3*/ virtual ~SwampBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*9*/ virtual int getFoliageColor(class BlockPos const &) const;
    /*12*/ virtual int getMapFoliageColor(class BlockPos const &) const;
    /*17*/ virtual int getGrassColor(class BlockPos const &) const;
    /*18*/ virtual int getMapGrassColor(class BlockPos const &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SWAMPBIOME
#endif

};