// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Biome.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TheEndBiome : public Biome {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_THEENDBIOME
public:
    class TheEndBiome& operator=(class TheEndBiome const &) = delete;
    TheEndBiome(class TheEndBiome const &) = delete;
    TheEndBiome() = delete;
#endif

public:
    /*3*/ virtual ~TheEndBiome();
    /*5*/ virtual void __unk_vfn_5();
    /*6*/ virtual void __unk_vfn_6();
    /*7*/ virtual class Color getSkyColor(float);
    /*16*/ virtual void decorate(class BlockSource *, class Random &, class BlockPos const &, bool, float);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_THEENDBIOME
#endif

};