// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ThreadSpecificData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_THREADSPECIFICDATA
public:
    class ThreadSpecificData& operator=(class ThreadSpecificData const &) = delete;
    ThreadSpecificData(class ThreadSpecificData const &) = delete;
    ThreadSpecificData() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_THREADSPECIFICDATA
#endif
    MCAPI ~ThreadSpecificData();

};