// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ThreadUtil {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_THREADUTIL
public:
    class ThreadUtil& operator=(class ThreadUtil const &) = delete;
    ThreadUtil(class ThreadUtil const &) = delete;
    ThreadUtil() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_THREADUTIL
#endif

//protected:

protected:
    MCAPI static unsigned int sNumAvailableCores;

};