// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class UnderwaterLargeCaveFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_UNDERWATERLARGECAVEFEATURE
public:
    class UnderwaterLargeCaveFeature& operator=(class UnderwaterLargeCaveFeature const &) = delete;
    UnderwaterLargeCaveFeature(class UnderwaterLargeCaveFeature const &) = delete;
    UnderwaterLargeCaveFeature() = delete;
#endif

public:
    /*0*/ virtual ~UnderwaterLargeCaveFeature();
    /*1*/ virtual bool carve(class BlockVolume &, class BiomeSource &, class Random &, class ChunkPos const &, class Vec3 const &, class Vec3 const &, int, int, int, int, int, int, float, float) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_UNDERWATERLARGECAVEFEATURE
#endif
    MCAPI static bool isDiggable(class Block const &);

};