// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Packet.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class UpdateAbilitiesPacket : public Packet {

#define AFTER_EXTRA

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_UPDATEABILITIESPACKET
public:
    class UpdateAbilitiesPacket& operator=(class UpdateAbilitiesPacket const &) = delete;
    UpdateAbilitiesPacket(class UpdateAbilitiesPacket const &) = delete;
#endif

public:
    /*0*/ virtual ~UpdateAbilitiesPacket();
    /*1*/ virtual enum MinecraftPacketIds getId() const;
    /*2*/ virtual std::string getName() const;
    /*3*/ virtual void write(class BinaryStream &) const;
    /*6*/ virtual enum StreamReadResult _read(class ReadOnlyBinaryStream &);
    /*
    inline  ~UpdateAbilitiesPacket(){
         (UpdateAbilitiesPacket::*rv)();
        *((void**)&rv) = dlsym("??1UpdateAbilitiesPacket@@UEAA@XZ");
        return (this->*rv)();
    }
    */
    MCAPI UpdateAbilitiesPacket(struct ActorUniqueID, class LayeredAbilities const &);
    MCAPI UpdateAbilitiesPacket();
    MCAPI void fillIn(class LayeredAbilities &) const;
    MCAPI struct ActorUniqueID getTargetPlayer() const;

protected:

private:
    MCAPI static class std::array<enum UpdateAbilitiesPacket::SerializedAbilitiesLayer, 2> const ABILITIES_LAYER_MAP;

};