// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

class WearableItemComponent {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA

#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WEARABLEITEMCOMPONENT
public:
    class WearableItemComponent& operator=(class WearableItemComponent const &) = delete;
    WearableItemComponent(class WearableItemComponent const &) = delete;
    WearableItemComponent() = delete;
#endif

public:
    /*0*/ virtual ~WearableItemComponent();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void __unk_vfn_3();
    MCAPI enum EquipmentSlot getSlot() const;
    MCAPI bool use(class ItemStack &, class Player &) const;
    MCAPI static void bindType();
    MCAPI static class HashedString const & getIdentifier();

protected:

private:

};