// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Whitelist {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WHITELIST
public:
    class Whitelist& operator=(class Whitelist const &) = delete;
    Whitelist(class Whitelist const &) = delete;
    Whitelist() = delete;
#endif

public:
    /*0*/ virtual ~Whitelist();
    /*1*/ virtual void serialize(class Json::Value &);
    /*2*/ virtual void deserialize(class Json::Value &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WHITELIST
#endif
    MCAPI bool isIgnoringPlayerLimit(class mce::UUID const &, std::string const &) const;
    MCAPI void tryUpdateEntries(class mce::UUID const &, std::string const &, std::string const &);

};