// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Command.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WhitelistCommand : public Command {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WHITELISTCOMMAND
public:
    class WhitelistCommand& operator=(class WhitelistCommand const &) = delete;
    WhitelistCommand(class WhitelistCommand const &) = delete;
    WhitelistCommand() = delete;
#endif

public:
    /*0*/ virtual ~WhitelistCommand();
    /*1*/ virtual void execute(class CommandOrigin const &, class CommandOutput &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WHITELISTCOMMAND
#endif
    MCAPI static void setup(class CommandRegistry &, class WhitelistFile &);

//private:

private:
    MCAPI static class WhitelistFile * mWhitelistFile;

};