// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WinStackTrace {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WINSTACKTRACE
public:
    class WinStackTrace& operator=(class WinStackTrace const &) = delete;
    WinStackTrace(class WinStackTrace const &) = delete;
    WinStackTrace() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WINSTACKTRACE
#endif
    MCAPI static std::string getStackTrace(struct _CONTEXT *);

};