// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WorldSystems {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WORLDSYSTEMS
public:
    class WorldSystems& operator=(class WorldSystems const &) = delete;
    WorldSystems(class WorldSystems const &) = delete;
    WorldSystems() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WORLDSYSTEMS
#endif
    MCAPI static void init(class ResourcePackManager *);
    MCAPI static bool mInitialized;

};