// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "ZipPackAccessStrategy.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ZipPackAccessStrategyOwningFileAcccess : public ZipPackAccessStrategy {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ZIPPACKACCESSSTRATEGYOWNINGFILEACCCESS
public:
    class ZipPackAccessStrategyOwningFileAcccess& operator=(class ZipPackAccessStrategyOwningFileAcccess const &) = delete;
    ZipPackAccessStrategyOwningFileAcccess(class ZipPackAccessStrategyOwningFileAcccess const &) = delete;
    ZipPackAccessStrategyOwningFileAcccess() = delete;
#endif

public:
    /*0*/ virtual ~ZipPackAccessStrategyOwningFileAcccess();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ZIPPACKACCESSSTRATEGYOWNINGFILEACCCESS
#endif
    MCAPI ZipPackAccessStrategyOwningFileAcccess(class std::shared_ptr<class IFileAccess>, class ResourceLocation const &, std::string const &);

};