// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class BatPostNormalTickSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BATPOSTNORMALTICKSYSTEM
public:
    class BatPostNormalTickSystem& operator=(class BatPostNormalTickSystem const &) = delete;
    BatPostNormalTickSystem(class BatPostNormalTickSystem const &) = delete;
    BatPostNormalTickSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BATPOSTNORMALTICKSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

};