// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here

#undef BEFORE_EXTRA

struct BlockMapColorDescription {

#define AFTER_EXTRA
// Add Member There

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BLOCKMAPCOLORDESCRIPTION
public:
    struct BlockMapColorDescription& operator=(struct BlockMapColorDescription const &) = delete;
    BlockMapColorDescription(struct BlockMapColorDescription const &) = delete;
    BlockMapColorDescription() = delete;
#endif
public:
    /*0*/ virtual ~BlockMapColorDescription();
    /*1*/ virtual std::string const & getName() const;
    /*2*/ virtual void initializeComponent(class EntityContext &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BLOCKMAPCOLORDESCRIPTION
#endif
    MCAPI static std::string const NameID;
    MCAPI static void bindType();
    MCAPI static void registerVersionUpgrades(class CerealSchemaUpgradeSet &);

};