// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ClientStopGlidingSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CLIENTSTOPGLIDINGSYSTEM
public:
    class ClientStopGlidingSystem& operator=(class ClientStopGlidingSystem const &) = delete;
    ClientStopGlidingSystem(class ClientStopGlidingSystem const &) = delete;
    ClientStopGlidingSystem() = delete;
#endif

public:
    /*0*/ virtual ~ClientStopGlidingSystem();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void tick(class StrictExecutionContext<struct Filter<class FlagComponent<struct ActorMovementTickNeededFlag>, class FlagComponent<struct PlayerComponentFlag>, class FlagComponent<struct UsesECSMovementFlag>>, struct Read<struct StateVectorComponent, struct CollisionBoxDefinitionComponent>, struct Write<struct AABBShapeComponent, struct OffsetsComponent, struct PlayerActionComponent, struct SynchedActorDataComponent>, struct AddRemove<class FlagComponent<struct StopGlidingRequestFlag>, class FlagComponent<struct WasPenetratingLastFrameFlag>>, struct GlobalRead<>, struct GlobalWrite<>, struct EntityFactoryT<>> &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CLIENTSTOPGLIDINGSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createClientStopGlidingSystem();

};