// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class CollidableMobNotifierSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_COLLIDABLEMOBNOTIFIERSYSTEM
public:
    class CollidableMobNotifierSystem& operator=(class CollidableMobNotifierSystem const &) = delete;
    CollidableMobNotifierSystem(class CollidableMobNotifierSystem const &) = delete;
    CollidableMobNotifierSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_COLLIDABLEMOBNOTIFIERSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();
    MCAPI static void tickNotifier(class StrictEntityContext &, struct AABBShapeComponent const &, struct SpatialEntityFetcherComponent const &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class FlagComponent<struct MobFlag>>>, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class FlagComponent<struct FallingBlockFlag>>>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct CollidableMobNearFlag>>);

};