// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct CurrentRailBlockDataComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CURRENTRAILBLOCKDATACOMPONENT
public:
    struct CurrentRailBlockDataComponent& operator=(struct CurrentRailBlockDataComponent const &) = delete;
    CurrentRailBlockDataComponent(struct CurrentRailBlockDataComponent const &) = delete;
    CurrentRailBlockDataComponent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CURRENTRAILBLOCKDATACOMPONENT
#endif
    MCAPI ~CurrentRailBlockDataComponent();

};