// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct EventingRequest {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EVENTINGREQUEST
public:
    struct EventingRequest& operator=(struct EventingRequest const &) = delete;
    EventingRequest(struct EventingRequest const &) = delete;
    EventingRequest() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EVENTINGREQUEST
#endif
    MCAPI ~EventingRequest();
    MCAPI static struct EventingRequest addPersonaEmotePlayed(std::string const &, bool, int);
    MCAPI static struct EventingRequest addPlayerBounced(struct ActorUniqueID const &, class Block const &, int);

};