// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ExitVehicleSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_EXITVEHICLESYSTEM
public:
    class ExitVehicleSystem& operator=(class ExitVehicleSystem const &) = delete;
    ExitVehicleSystem(class ExitVehicleSystem const &) = delete;
    ExitVehicleSystem() = delete;
#endif

public:
    /*0*/ virtual ~ExitVehicleSystem();
    /*1*/ virtual void __unk_vfn_1();
    /*2*/ virtual void __unk_vfn_2();
    /*3*/ virtual void tick(class StrictExecutionContext<struct Filter<class FlagComponent<struct HasLightweightFamilyFlag>, class FlagComponent<struct IsWearingLeatherBoots>, class FlagComponent<struct IsWorldBuilderFlag>, class FlagComponent<struct HorseFlag>, class FlagComponent<struct MobFlag>, class FlagComponent<struct ParrotFlag>, struct VehicleComponent, class FlagComponent<struct PlayerComponentFlag>, class FlagComponent<struct ExitFromPassengerFlag>, class FlagComponent<struct StopRidingRequestFlag>>, struct Read<struct ActorTypeComponent, struct FallDistanceComponent, struct MobBodyRotationComponent, struct RenderRotationComponent, struct StandAnimationComponent, struct AABBShapeComponent, struct ActorHeadRotationComponent, struct ActorRotationComponent, struct OffsetsComponent, struct StateVectorComponent, struct SynchedActorDataComponent, struct ConstBlockSourceComponent, struct PassengerComponent, struct VehicleComponent>, struct Write<struct AABBShapeComponent, struct ActorRotationComponent, struct StateVectorComponent>, struct AddRemove<struct ActorMoveToRequestComponent, struct ActorSetPositionRequestComponent>, struct GlobalRead<struct BaseGameVersionComponent>, struct GlobalWrite<>, struct EntityFactoryT<>> &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_EXITVEHICLESYSTEM
#endif
    MCAPI static void _tickExitVehicle(class StrictEntityContext &, struct ConstBlockSourceComponent const &, struct PassengerComponent const &, struct AABBShapeComponent &, struct ActorRotationComponent &, struct StateVectorComponent &, class BaseGameVersion const &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct VehicleComponent const, struct StateVectorComponent const>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ActorMoveToRequestComponent, struct ActorSetPositionRequestComponent> &, class StrictExecutionContext<struct Filter<class FlagComponent<struct HasLightweightFamilyFlag>, class FlagComponent<struct IsWearingLeatherBoots>, class FlagComponent<struct IsWorldBuilderFlag>, class FlagComponent<struct HorseFlag>, class FlagComponent<struct MobFlag>, class FlagComponent<struct ParrotFlag>, struct VehicleComponent, class FlagComponent<struct PlayerComponentFlag>, class FlagComponent<struct ExitFromPassengerFlag>, class FlagComponent<struct StopRidingRequestFlag>>, struct Read<struct ActorTypeComponent, struct FallDistanceComponent, struct MobBodyRotationComponent, struct RenderRotationComponent, struct StandAnimationComponent, struct AABBShapeComponent, struct ActorHeadRotationComponent, struct ActorRotationComponent, struct OffsetsComponent, struct StateVectorComponent, struct SynchedActorDataComponent, struct ConstBlockSourceComponent, struct PassengerComponent, struct VehicleComponent>, struct Write<struct AABBShapeComponent, struct ActorRotationComponent, struct StateVectorComponent>, struct AddRemove<struct ActorMoveToRequestComponent, struct ActorSetPositionRequestComponent>, struct GlobalRead<struct BaseGameVersionComponent>, struct GlobalWrite<>, struct EntityFactoryT<>> &);
    MCAPI static struct TickingSystemWithInfo createSystem();

};