// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class GetAttachPosSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GETATTACHPOSSYSTEM
public:
    class GetAttachPosSystem& operator=(class GetAttachPosSystem const &) = delete;
    GetAttachPosSystem(class GetAttachPosSystem const &) = delete;
    GetAttachPosSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GETATTACHPOSSYSTEM
#endif
    MCAPI static class std::optional<class Vec3> getAttachPos(class StrictEntityContext const &, enum ActorLocation, class Vec3 const &, struct AABBShapeComponent const &, struct ActorHeadRotationComponent const &, struct ActorRotationComponent const &, struct OffsetsComponent const &, struct StateVectorComponent const &, struct SynchedActorDataComponent const &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class FlagComponent<struct PlayerComponentFlag>>>);
    MCAPI static class std::optional<class Vec3> getBaseAttachPoint(struct AABBShapeComponent const &, struct ActorHeadRotationComponent const &, struct ActorRotationComponent const &, struct OffsetsComponent const &, struct StateVectorComponent const &, struct GetAttachPosRequestData &);

};