// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class GossipType {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_GOSSIPTYPE
public:
    class GossipType& operator=(class GossipType const &) = delete;
    GossipType(class GossipType const &) = delete;
    GossipType() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_GOSSIPTYPE
#endif
    MCAPI GossipType(std::string const &, int, int, int, int, int);
    MCAPI ~GossipType();
    MCAPI static std::string const MAJOR_NEGATIVE;
    MCAPI static std::string const MAJOR_POSITIVE;
    MCAPI static std::string const MINOR_NEGATIVE;
    MCAPI static std::string const MINOR_POSITIVE;
    MCAPI static std::string const TRADING;
    MCAPI static class GossipType const UNRECOGNIZED;
    MCAPI static class GossipType tryCreateFromJSON(class Json::Value const &);

};