// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ItemUseSlowdownSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ITEMUSESLOWDOWNSYSTEM
public:
    class ItemUseSlowdownSystem& operator=(class ItemUseSlowdownSystem const &) = delete;
    ItemUseSlowdownSystem(class ItemUseSlowdownSystem const &) = delete;
    ItemUseSlowdownSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ITEMUSESLOWDOWNSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createItemUseSlowdownRequestSystem();
    MCAPI static struct TickingSystemWithInfo createItemUseSlowdownSystem();
    MCAPI static struct TickingSystemWithInfo createResetSprintTriggerTimeSystem();

//private:
    MCAPI static void doItemUseSlowdownRequestSystem(class StrictEntityContext const &, struct SlowdownByItemInUseRequestComponent const &, struct MoveInputComponent &);
    MCAPI static void doItemUseSlowdownSystem(class StrictEntityContext const &, class Optional<struct ItemInUseComponent const>, struct MoveInputComponent &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct SlowdownByItemInUseRequestComponent>);
    MCAPI static void doResetSprintTriggerTimeSystem(class StrictEntityContext const &, struct VanillaClientGameplayComponent &);

private:

};