// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LiquidSplashSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LIQUIDSPLASHSYSTEM
public:
    class LiquidSplashSystem& operator=(class LiquidSplashSystem const &) = delete;
    LiquidSplashSystem(class LiquidSplashSystem const &) = delete;
    LiquidSplashSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LIQUIDSPLASHSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

};