// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LiquidPhysicsSystemImpl {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LIQUIDPHYSICSSYSTEMIMPL
public:
    class LiquidPhysicsSystemImpl& operator=(class LiquidPhysicsSystemImpl const &) = delete;
    LiquidPhysicsSystemImpl(class LiquidPhysicsSystemImpl const &) = delete;
    LiquidPhysicsSystemImpl() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LIQUIDPHYSICSSYSTEMIMPL
#endif
    MCAPI static void _applyFlow(struct StateVectorComponent &, class Vec3, enum MaterialType);
    MCAPI static void _getLiquidBlocksInAABB(std::vector<struct LiquidBlockEntry> &, class IConstBlockSource const &, class AABB const &, enum MaterialType);
    MCAPI static bool _hasAdjacentFlowingBlock(std::vector<struct LiquidBlockEntry> const &, class IConstBlockSource const &, enum MaterialType);
    MCAPI static bool _hasFlowingBlock(std::vector<struct LiquidBlockEntry> const &);

};