// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class LiquidSensingSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_LIQUIDSENSINGSYSTEM
public:
    class LiquidSensingSystem& operator=(class LiquidSensingSystem const &) = delete;
    LiquidSensingSystem(class LiquidSensingSystem const &) = delete;
    LiquidSensingSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_LIQUIDSENSINGSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createFlagResetSystem();
    MCAPI static struct TickingSystemWithInfo createSensingSideBySideSystem();
    MCAPI static struct TickingSystemWithInfo createSensingSystem();

//private:
    MCAPI static void _sensingSideBySide(class StrictEntityContext const &, struct SideBySideLiquidSensingComponent const &, struct UpdateWaterStateRequestComponent &);

private:

};