// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace MineshaftUtil {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI bool _isLava(class BlockLegacy const &);
    MCAPI void fillColumnBetween(class BlockSource &, class Block const &, class BlockPos const &, int, int);
    MCAPI bool isCavesAndCliffs(class Level const &);

};