// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MinecartMoveAlongRailSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MINECARTMOVEALONGRAILSYSTEM
public:
    class MinecartMoveAlongRailSystem& operator=(class MinecartMoveAlongRailSystem const &) = delete;
    MinecartMoveAlongRailSystem(class MinecartMoveAlongRailSystem const &) = delete;
    MinecartMoveAlongRailSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MINECARTMOVEALONGRAILSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createCleanupSystem();
    MCAPI static struct TickingSystemWithInfo createExtractCurrentRailBlockDataSystem();
    MCAPI static struct TickingSystemWithInfo createPostRailMovementPositionSystem();
    MCAPI static struct TickingSystemWithInfo createPreRailMovementPositionSystem();
    MCAPI static struct TickingSystemWithInfo createRailMovementSystem();

//private:
    MCAPI static void _calculateRailMovementSystem(class StrictEntityContext &, class RailMovementComponent const &, struct CurrentRailBlockDataComponent const &, struct SnapOnRailComponent &, struct StateVectorComponent &, class Optional<struct VehicleComponent const>, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class FlagComponent<struct PlayerComponentFlag>>, struct ActorRotationComponent const, struct LocalMoveVelocityComponent const>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct MoveRequestComponent>);
    MCAPI static void _extractSideBySideRailBlockData(class StrictEntityContext &, struct ConstBlockSourceComponent const &, struct SnapOnRailComponent const &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct CurrentRailBlockDataComponent>);
    MCAPI static void _postRailMovementCalculateMinecartPositionSystem(class StrictEntityContext &, struct ConstBlockSourceComponent const &, struct SnapOnRailComponent const &, struct StateVectorComponent &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ActorSetPositionRequestComponent>);
    MCAPI static void _preRailMovementCalculateMinecartPositionSystem(class StrictEntityContext &, struct ConstBlockSourceComponent const &, struct OffsetsComponent const &, struct StateVectorComponent const &, struct FallDistanceComponent &, struct SnapOnRailComponent &, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ActorSetPositionRequestComponent>);
    MCAPI static void _tickPreRailMovementCalculateMinecartPositionSystem(class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class RailMovementComponent>, struct ConstBlockSourceComponent const, struct OffsetsComponent const, struct StateVectorComponent const, struct FallDistanceComponent, struct SnapOnRailComponent>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ActorSetPositionRequestComponent>);

private:

};