// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ModuleIdentifier {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MODULEIDENTIFIER
public:
    struct ModuleIdentifier& operator=(struct ModuleIdentifier const &) = delete;
    ModuleIdentifier(struct ModuleIdentifier const &) = delete;
    ModuleIdentifier() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MODULEIDENTIFIER
#endif
    MCAPI ~ModuleIdentifier();

};