// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Json.hpp"
#include "ItemDescriptorCount.hpp"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here
#include "ItemDescriptor.hpp"
#include "ItemStackNetIdVariant.hpp"

#undef BEFORE_EXTRA

class NetworkItemStackDescriptor : public ItemDescriptorCount {

#define AFTER_EXTRA
// Add Member There
public:
    char filler[72];
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_NETWORKITEMSTACKDESCRIPTOR
public:
    class NetworkItemStackDescriptor& operator=(class NetworkItemStackDescriptor const &) = delete;
#endif

public:
    /*0*/ virtual ~NetworkItemStackDescriptor();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_NETWORKITEMSTACKDESCRIPTOR
#endif
    MCAPI NetworkItemStackDescriptor(class ItemStackDescriptor const &);
    MCAPI NetworkItemStackDescriptor(class ItemStack const &);
    MCAPI NetworkItemStackDescriptor();
    MCAPI NetworkItemStackDescriptor(class NetworkItemStackDescriptor const &);
    MCAPI NetworkItemStackDescriptor(class NetworkItemStackDescriptor &&);
    MCAPI void read(class ReadOnlyBinaryStream &);
    MCAPI void setIncludeNetIds(bool) const;
    MCAPI class TypedServerNetId<struct ItemStackNetIdTag, int, 0> const * tryGetServerNetId() const;
    MCAPI void write(class BinaryStream &) const;

//private:
    MCAPI class ItemStack getItemStack(class BlockPalette const &) const;

private:

};