// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class PostFallDamageFinalizeMoveSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_POSTFALLDAMAGEFINALIZEMOVESYSTEM
public:
    class PostFallDamageFinalizeMoveSystem& operator=(class PostFallDamageFinalizeMoveSystem const &) = delete;
    PostFallDamageFinalizeMoveSystem(class PostFallDamageFinalizeMoveSystem const &) = delete;
    PostFallDamageFinalizeMoveSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_POSTFALLDAMAGEFINALIZEMOVESYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createPostFallDamageFinalizeMoveSystem();

};