// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct PropertySyncData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_PROPERTYSYNCDATA
public:
    struct PropertySyncData& operator=(struct PropertySyncData const &) = delete;
    PropertySyncData(struct PropertySyncData const &) = delete;
    PropertySyncData() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_PROPERTYSYNCDATA
#endif
    MCAPI struct PropertySyncData & operator=(struct PropertySyncData &&);
    MCAPI ~PropertySyncData();

};