// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ResetJumpRidingScaleSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESETJUMPRIDINGSCALESYSTEM
public:
    class ResetJumpRidingScaleSystem& operator=(class ResetJumpRidingScaleSystem const &) = delete;
    ResetJumpRidingScaleSystem(class ResetJumpRidingScaleSystem const &) = delete;
    ResetJumpRidingScaleSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESETJUMPRIDINGSCALESYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

//private:
    MCAPI static void _doResetJumpRidingScaleSystem(class StrictEntityContext const &, struct JumpRidingScaleComponent &, struct VanillaClientGameplayComponent &);

private:

};