// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ResetActionStopSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESETACTIONSTOPSYSTEM
public:
    class ResetActionStopSystem& operator=(class ResetActionStopSystem const &) = delete;
    ResetActionStopSystem(class ResetActionStopSystem const &) = delete;
    ResetActionStopSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESETACTIONSTOPSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createResetActionStopSystem();

};