// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ResourceDropsContext {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESOURCEDROPSCONTEXT
public:
    struct ResourceDropsContext& operator=(struct ResourceDropsContext const &) = delete;
    ResourceDropsContext(struct ResourceDropsContext const &) = delete;
    ResourceDropsContext() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESOURCEDROPSCONTEXT
#endif
    MCAPI ResourceDropsContext(float, class ItemStack const &);

};