// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ResolvedItemIconInfo {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESOLVEDITEMICONINFO
public:
    struct ResolvedItemIconInfo& operator=(struct ResolvedItemIconInfo const &) = delete;
    ResolvedItemIconInfo(struct ResolvedItemIconInfo const &) = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESOLVEDITEMICONINFO
#endif
    MCAPI ResolvedItemIconInfo();
    MCAPI ResolvedItemIconInfo(unsigned int, int);
    MCAPI ResolvedItemIconInfo(std::string const &, float, float, float, float, unsigned short, unsigned short);
    MCAPI ResolvedItemIconInfo(std::string const &, int, enum ItemIconInfoType);
    MCAPI ~ResolvedItemIconInfo();

};