// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RideJumpTriggerSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RIDEJUMPTRIGGERSYSTEM
public:
    class RideJumpTriggerSystem& operator=(class RideJumpTriggerSystem const &) = delete;
    RideJumpTriggerSystem(class RideJumpTriggerSystem const &) = delete;
    RideJumpTriggerSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RIDEJUMPTRIGGERSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

//private:
    MCAPI static void _tickRideJumpTriggerSystem(class StrictEntityContext &, struct MoveInputComponent const &, struct PassengerComponent const &, struct JumpRidingScaleComponent &, struct VanillaClientGameplayComponent &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct VehicleComponent const, struct SynchedActorDataComponent const, class Optional<class FlagComponent<struct MobFlag> const>, class Optional<class FlagComponent<struct OnGroundFlag> const>, class Optional<struct PassengerComponent const>>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct MobOnPlayerJumpRequestComponent, struct SendPacketsComponent> &);

private:

};