// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScaffoldingSensingSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCAFFOLDINGSENSINGSYSTEM
public:
    class ScaffoldingSensingSystem& operator=(class ScaffoldingSensingSystem const &) = delete;
    ScaffoldingSensingSystem(class ScaffoldingSensingSystem const &) = delete;
    ScaffoldingSensingSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCAFFOLDINGSENSINGSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createScaffoldingSensingSystem();

};