// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptingInitializeEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTINGINITIALIZEEVENT
public:
    class ScriptingInitializeEvent& operator=(class ScriptingInitializeEvent const &) = delete;
    ScriptingInitializeEvent(class ScriptingInitializeEvent const &) = delete;
    ScriptingInitializeEvent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTINGINITIALIZEEVENT
#endif
    MCAPI ~ScriptingInitializeEvent();

};