// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Scripting.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ScriptUtils {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI struct Scripting::Error functionError(std::string const &);
    MCAPI struct Scripting::Error getPropertyError(std::string const &);
    MCAPI struct Scripting::Error setPropertyError(std::string const &);

};