// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Scripting.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ScriptModuleMinecraft {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI class Scripting::ClassBindingBuilder<class BlockPos> bindBlockLocation();
    MCAPI class Scripting::EnumBindingBuilder<enum ScriptModuleMinecraft::ScriptFacing, enum ScriptModuleMinecraft::ScriptFacing> bindFacingEnumV010();
    MCAPI class Scripting::EnumBindingBuilder<std::string, enum ScriptModuleMinecraft::ScriptFacing> bindFacingEnumV1();
    MCAPI class Scripting::EnumBindingBuilder<enum ScriptModuleMinecraft::ScriptMessageSourceType, enum ScriptModuleMinecraft::ScriptMessageSourceType> bindMessageSourceTypeV010();
    MCAPI class Scripting::EnumBindingBuilder<std::string, enum ScriptModuleMinecraft::ScriptMessageSourceType> bindMessageSourceTypeV1();
    MCAPI class Scripting::EnumBindingBuilder<enum ScriptModuleMinecraft::ScriptTimeOfDay, enum ScriptModuleMinecraft::ScriptTimeOfDay> bindTimeOfDay();

};