// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Scripting.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace ScriptMemory {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI std::unique_ptr<struct Scripting::QuickJS::MallocFunctions> getQuickJSMallocFunctions();

};