// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Scripting.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ScriptBindingReleaseList {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SCRIPTBINDINGRELEASELIST
public:
    class ScriptBindingReleaseList& operator=(class ScriptBindingReleaseList const &) = delete;
    ScriptBindingReleaseList(class ScriptBindingReleaseList const &) = delete;
    ScriptBindingReleaseList() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SCRIPTBINDINGRELEASELIST
#endif
    MCAPI ScriptBindingReleaseList(std::vector<struct std::pair<char const *const *, struct Scripting::Version>>);

};