// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ServerPlayerFallDamageSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERPLAYERFALLDAMAGESYSTEM
public:
    class ServerPlayerFallDamageSystem& operator=(class ServerPlayerFallDamageSystem const &) = delete;
    ServerPlayerFallDamageSystem(class ServerPlayerFallDamageSystem const &) = delete;
    ServerPlayerFallDamageSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERVERPLAYERFALLDAMAGESYSTEM
#endif
    MCAPI static void _doServerPlayerFallDamageSystem(class StrictEntityContext const &, struct AbilitiesComponent const &, struct SynchedActorDataComponent const &, struct StateVectorComponent const &, struct FallDistanceComponent &, class Optional<class FlagComponent<struct WasOnGroundFlag> const>, class Optional<class FlagComponent<struct OnGroundFlag> const>, class Optional<class FlagComponent<struct HasTeleportedFlag> const>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct HasTeleportedFlag>, class FlagComponent<struct SendPlayerOnGroundRequestFlag>, struct CheckFallDamageRequestComponent, class FlagComponent<struct WasOnGroundFlag>>);
    MCAPI static struct TickingSystemWithInfo createSystem();

};