// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct ServerPlayerMovementComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERPLAYERMOVEMENTCOMPONENT
public:
    struct ServerPlayerMovementComponent& operator=(struct ServerPlayerMovementComponent const &) = delete;
    ServerPlayerMovementComponent(struct ServerPlayerMovementComponent const &) = delete;
    ServerPlayerMovementComponent() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERVERPLAYERMOVEMENTCOMPONENT
#endif
    MCAPI ServerPlayerMovementComponent(struct ServerPlayerMovementComponent &&);
    MCAPI ~ServerPlayerMovementComponent();

};