// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ServerStandInCauldronSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SERVERSTANDINCAULDRONSYSTEM
public:
    class ServerStandInCauldronSystem& operator=(class ServerStandInCauldronSystem const &) = delete;
    ServerStandInCauldronSystem(class ServerStandInCauldronSystem const &) = delete;
    ServerStandInCauldronSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SERVERSTANDINCAULDRONSYSTEM
#endif
    MCAPI static void _checkInsideCauldron(class StrictEntityContext &, class ActorOwnerComponent &);
    MCAPI static struct TickingSystemWithInfo createSystem();

};