// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ShulkerUpdatePositionSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SHULKERUPDATEPOSITIONSYSTEM
public:
    class ShulkerUpdatePositionSystem& operator=(class ShulkerUpdatePositionSystem const &) = delete;
    ShulkerUpdatePositionSystem(class ShulkerUpdatePositionSystem const &) = delete;
    ShulkerUpdatePositionSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SHULKERUPDATEPOSITIONSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createShulkerUpdatePositionSystem();

};