// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SideBySideMigrationSystemImpl {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SIDEBYSIDEMIGRATIONSYSTEMIMPL
public:
    class SideBySideMigrationSystemImpl& operator=(class SideBySideMigrationSystemImpl const &) = delete;
    SideBySideMigrationSystemImpl(class SideBySideMigrationSystemImpl const &) = delete;
    SideBySideMigrationSystemImpl() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SIDEBYSIDEMIGRATIONSYSTEMIMPL
#endif

};