// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SimulatedPlayerPreAIStepSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SIMULATEDPLAYERPREAISTEPSYSTEM
public:
    class SimulatedPlayerPreAIStepSystem& operator=(class SimulatedPlayerPreAIStepSystem const &) = delete;
    SimulatedPlayerPreAIStepSystem(class SimulatedPlayerPreAIStepSystem const &) = delete;
    SimulatedPlayerPreAIStepSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SIMULATEDPLAYERPREAISTEPSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

//private:
    MCAPI static void _doSimulatedPlayerPreAIStepSystem(class StrictEntityContext const &, class ActorOwnerComponent &);

private:

};