// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SkeletonPassengerRotationSystemImpl {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SKELETONPASSENGERROTATIONSYSTEMIMPL
public:
    class SkeletonPassengerRotationSystemImpl& operator=(class SkeletonPassengerRotationSystemImpl const &) = delete;
    SkeletonPassengerRotationSystemImpl(class SkeletonPassengerRotationSystemImpl const &) = delete;
    SkeletonPassengerRotationSystemImpl() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SKELETONPASSENGERROTATIONSYSTEMIMPL
#endif

//private:
    MCAPI static void _tickSkeletonView(class StrictEntityContext &, struct PassengerComponent const &, class FlagComponent<struct SkeletonFlag> const &, struct MobBodyRotationComponent &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct VehicleComponent const, struct MobBodyRotationComponent const>);

private:

};