// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace snappy {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI unsigned __int64 Compress(class snappy::Source *, class snappy::Sink *);
    MCAPI unsigned __int64 Compress(char const *, unsigned __int64, std::string *);
    MCAPI bool Uncompress(char const *, unsigned __int64, std::string *);

};