// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SneakInputSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SNEAKINPUTSYSTEM
public:
    class SneakInputSystem& operator=(class SneakInputSystem const &) = delete;
    SneakInputSystem(class SneakInputSystem const &) = delete;
    SneakInputSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SNEAKINPUTSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSneakInputSystem();

};