// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct SystemInfo {

#define AFTER_EXTRA

#undef AFTER_EXTRApublic:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SYSTEMINFO
#endif
    MCAPI SystemInfo();
    MCAPI SystemInfo(struct SystemInfo const &);
    MCAPI struct SystemInfo & operator=(struct SystemInfo const &);
    MCAPI struct SystemInfo & operator=(struct SystemInfo &&);
    MCAPI ~SystemInfo();
    MCAPI static void bindType();

};