// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TeleportInterpolatorResetSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TELEPORTINTERPOLATORRESETSYSTEM
public:
    class TeleportInterpolatorResetSystem& operator=(class TeleportInterpolatorResetSystem const &) = delete;
    TeleportInterpolatorResetSystem(class TeleportInterpolatorResetSystem const &) = delete;
    TeleportInterpolatorResetSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_TELEPORTINTERPOLATORRESETSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createTeleportInterpolatorResetSystem();

};