// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TryExitVehicleSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TRYEXITVEHICLESYSTEM
public:
    class TryExitVehicleSystem& operator=(class TryExitVehicleSystem const &) = delete;
    TryExitVehicleSystem(class TryExitVehicleSystem const &) = delete;
    TryExitVehicleSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_TRYEXITVEHICLESYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

//private:
    MCAPI static void _tickTryExitVehicle(class StrictEntityContext &, struct PassengerComponent const &, struct AbilitiesComponent const &, struct MobJumpComponent const &, class ViewT<class StrictEntityContext, class EntityRegistryBase, struct Include<class FlagComponent<struct ActorMovementTickNeededFlag>, class FlagComponent<struct UsesECSMovementFlag>, struct VehicleComponent>, struct Exclude<class FlagComponent<struct BoatFlag>>, class Optional<class FlagComponent<struct MobFlag> const>, class Optional<struct AttributesComponent const>, struct SynchedActorDataComponent const>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, class FlagComponent<struct StopRidingRequestFlag>, class FlagComponent<struct ExitFromPassengerFlag>> &);

private:

};