// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Packet.hpp"

#define BEFORE_EXTRA
#include "SerializedAbilitiesData.hpp"
#undef BEFORE_EXTRA

class UpdateAbilitiesPacket : public Packet {

#define AFTER_EXTRA
public:
	SerializedAbilitiesData mData;
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_UPDATEABILITIESPACKET
public:
    class UpdateAbilitiesPacket& operator=(class UpdateAbilitiesPacket const &) = delete;
    UpdateAbilitiesPacket(class UpdateAbilitiesPacket const &) = delete;
#endif

public:
    /*0*/ virtual ~UpdateAbilitiesPacket();
    /*1*/ virtual enum MinecraftPacketIds getId() const;
    /*2*/ virtual std::string getName() const;
    /*3*/ virtual void write(class BinaryStream &) const;
    /*6*/ virtual enum StreamReadResult _read(class ReadOnlyBinaryStream &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_UPDATEABILITIESPACKET
#endif
    MCAPI UpdateAbilitiesPacket();
    MCAPI UpdateAbilitiesPacket(struct ActorUniqueID, class LayeredAbilities const &);

};