// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class UpdateEntityAfterFallOnEntityProxyBase {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_UPDATEENTITYAFTERFALLONENTITYPROXYBASE
public:
    class UpdateEntityAfterFallOnEntityProxyBase& operator=(class UpdateEntityAfterFallOnEntityProxyBase const &) = delete;
    UpdateEntityAfterFallOnEntityProxyBase(class UpdateEntityAfterFallOnEntityProxyBase const &) = delete;
    UpdateEntityAfterFallOnEntityProxyBase() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_UPDATEENTITYAFTERFALLONENTITYPROXYBASE
#endif
    MCAPI static class Vec3 mDummy;

};