// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class VehicleClientPositionPassengerSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_VEHICLECLIENTPOSITIONPASSENGERSYSTEM
public:
    class VehicleClientPositionPassengerSystem& operator=(class VehicleClientPositionPassengerSystem const &) = delete;
    VehicleClientPositionPassengerSystem(class VehicleClientPositionPassengerSystem const &) = delete;
    VehicleClientPositionPassengerSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_VEHICLECLIENTPOSITIONPASSENGERSYSTEM
#endif
    MCAPI static void _setPositionRequest(class ViewedEntityContextT<class StrictEntityContext, struct SynchedActorDataComponent const>, class ViewedEntityContextT<class StrictEntityContext, struct RenderPositionComponent const, struct RenderRotationComponent const>, class EntityModifierT<class EntityRegistryBase, class StrictEntityContext, struct ActorSetPositionRequestComponent>);
    MCAPI static void _setRotationLock(class ViewedEntityContextT<class StrictEntityContext, struct SynchedActorDataComponent const, struct ActorHeadRotationComponent const, struct MobBodyRotationComponent, struct PassengerYRotLimitComponent>, class ViewedEntityContextT<class StrictEntityContext, struct RenderRotationComponent const>);
    MCAPI static struct TickingSystemWithInfo createSetPositionRequestSystem();
    MCAPI static struct TickingSystemWithInfo createSetPreviousPosRotSystem();
    MCAPI static struct TickingSystemWithInfo createSetRotationLock();

};