// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class WolfPostNormalTickSystem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WOLFPOSTNORMALTICKSYSTEM
public:
    class WolfPostNormalTickSystem& operator=(class WolfPostNormalTickSystem const &) = delete;
    WolfPostNormalTickSystem(class WolfPostNormalTickSystem const &) = delete;
    WolfPostNormalTickSystem() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WOLFPOSTNORMALTICKSYSTEM
#endif
    MCAPI static struct TickingSystemWithInfo createSystem();

//private:
    MCAPI static void _doWolfPostNormalTickSystem(class StrictEntityContext const &, class ActorOwnerComponent &);

private:

};